
on:
  workflow_dispatch:
  schedule:
  - cron: '18 1 * * *'
  

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: writ

    steps:
    - uses: actions/stale@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 14
        stale-issue-message: 'Due to inactivity, this issue will be closed in 7 days. Thank you for your contributions.'
        stale-pr-message: 'Due to inactivity, this pull request will be closed in 7 days. Thank you for your contributions.'
